services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tafel
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: tafel-operations-app-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./api:/code/api
    environment:
      - WATCHFILES_FORCE_POLLING=true

  frontend:
    build:
       context: .
       dockerfile: docker/Dockerfile.frontend
    image: tafel-operations-frontend
    volumes:
      - ./:/react-docker:delegated
      - /node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
