"""Add routing tables

Revision ID: 7793233d5fe4
Revises: dbb673d2fb0b
Create Date: 2023-05-30 16:27:07.468744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7793233d5fe4'
down_revision = 'dbb673d2fb0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type in ('customers', 'suppliers')", name='type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('prev', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prev'], ['routes_nodes.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes_nodes')
    op.drop_table('routes')
    # ### end Alembic commands ###
